# Generated by Django 5.0.1 on 2024-01-22 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breed', '0001_initial'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_tag_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('gender', models.CharField(choices=[('F', 'ماده'), ('M', 'نر')], max_length=1, verbose_name='جنسیت')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='وزن')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='قد')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cattle_photos/', verbose_name='عکس')),
                ('microchip_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره میکروچیپ')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breed.breed', verbose_name='نژاد')),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattle_dam', to='cattle.cattle', verbose_name='مادر حیوان')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner', verbose_name='صاحب')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattle_sire', to='cattle.cattle', verbose_name='پدر حیوان')),
            ],
            options={
                'verbose_name': 'گاو',
                'verbose_name_plural': 'گاو ها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField(verbose_name='تاریخ پرورش')),
                ('expected_calving_date', models.DateField(verbose_name='تاریخ زایمان مورد انتظار')),
                ('actual_calving_date', models.DateField(blank=True, null=True, verbose_name='تاریخ زایمان واقعی')),
                ('breeding_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='روش پرورش')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('bull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_bull', to='cattle.cattle', verbose_name='نر')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_cow', to='cattle.cattle', verbose_name='ماده')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField(verbose_name='تاریخ چک')),
                ('health_notes', models.TextField(verbose_name='یادداشت')),
                ('vaccinations', models.TextField(blank=True, null=True, verbose_name='واکسیناسیون')),
                ('treatments', models.TextField(blank=True, null=True, verbose_name='درمان ها')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='تشخیص')),
                ('veterinarian', models.CharField(blank=True, max_length=255, null=True, verbose_name='دامپزشک')),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.cattle', verbose_name='گاو')),
            ],
        ),
    ]
