# Generated by Django 5.0.1 on 2024-01-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=50, verbose_name='شماره موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت')),
                ('website', models.URLField(blank=True, null=True, verbose_name='آدرس وبسایت')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='owner_profiles/', verbose_name='عکس پروفایل')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صاحب',
                'verbose_name_plural': 'صاحب ها',
                'ordering': ['-created'],
            },
        ),
    ]
